homeassistant:
  # Name of the location where Home Assistant is running
  name: All
  # Location required to calculate the time the sun rises and sets
  latitude: !secret config_latitude
  longitude: !secret config_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4280 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# iOS App
ios:

# Add Plex Media Server
media_player:
  - platform: plex

# Adds ifttt integrations
ifttt:
  key: !secret config_ifttt

# Include these directories and files
automation: !include_dir_merge_list automation
device_tracker: !include device_tracker.yaml
group: !include group.yaml
notify: !include notify.yaml
sensor: !include sensor.yaml
