homeassistant:
  # Name of the location where Home Assistant is running
  name: All
  # Location required to calculate the time the sun rises and sets
  latitude: !secret config_latitude
  longitude: !secret config_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4280 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # Include customizations
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# UI api configuration
http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.10.1.0/24
    - 10.71.1.0/24
    - 10.71.2.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# iOS App
ios:

# Add Plex Media Server
media_player:
  - platform: plex

# Adds ifttt integrations
ifttt:
  key: !secret config_ifttt

# Include these directories and files
automation: !include_dir_merge_list automations
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
notify: !include notify.yaml
sensor: !include sensor.yaml
zwave: !include zwave.yaml
