- platform: darksky
  api_key: !secret sensor_darksky
  monitored_conditions:
    - summary
    - temperature
    - nearest_storm_distance
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - visibility
    - hourly_summary
    - daily_summary

- platform: rest
  resource: http://ip.jsontest.com
  name: external_ip
  value_template: '{{ value_json.ip }}'
  scan_interval: 86400

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: waqi
  token: !secret sensor_waqi
  locations:
    - !secret sensor_location
