# Home Assistant Server Metrics Package
homeassistant:
  customize:  
    package.node_anchors:
      customize: &customize
        package: 'homeassistant'

    sensor.cpu_used:
      friendly_name: CPU Used
    sensor.disk_free_:
      friendly_name: Disk Free Space
    sensor.ram_free:
      friendly_name: Available Memory
    sensor.last_boot:
      friendly_name: Last Boot
    sensor.since_last_boot:
      friendly_name: Up Since
    sensor.signal_strength:
      icon: mdi:signal
    sensor.link_quality:
      icon: mdi:link-variant
    sensor.ha_installed_version:
      icon: mdi:home-assistant
    sensor.ha_current_version:
      icon: mdi:home-assistant
    sensor.ha_last_restart:
      icon: mdi:home-assistant

    script.update_hass:
      friendly_name: Update Home Assistant
      icon: mdi:home-assistant
    script.restart_hass:
      friendly_name: Restart Home Assistant
      icon: mdi:home-assistant

group:
  homeassistant:
    name: HomeAssistant Metrics
    entities:
      - sensor.cpu_used
      - sensor.ram_free
      - sensor.disk_free_
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.cpu_temperature
      - sensor.signal_strength
      - sensor.link_quality
      - sensor.current_log_level
      - sensor.ram_available
      - sensor.ha_installed_version
      - sensor.ha_current_version
      - sensor.home_assistant_up_time

  update_hass:
    name: Update & Restart HA
    entities:
      - script.update_hass
      - script.restart_hass

script:
  update_hass:
    sequence:
      - service: shell_command.update_hass
  restart_hass:
    sequence:
      - service: shell_command.restart_hass

shell_command:
  restart_hass: >-
    hassctl restart
  update_hass: >-
    hassctl update-hass && hassctl config && hassctl restart

sensor:

  - platform: uptime
    name: Home Assistant Up Time
    unit_of_measurement: hours

  - platform: command_line
    name: CPU Temperature
    command: cat /sys/class/thermal/thermal_zone0/temp
    unit_of_measurement: 'F'
    value_template: '{{ (value|int / 1000 * 1.8 + 32)|round(1) }}'

  - platform: systemmonitor
    name: hass
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: since_last_boot

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA Current Version
    value_template: '{{ value_json.info.version }}'

  - platform: command_line
    name: HA Installed Version
    command: /srv/homeassistant/bin/hass --version
    scan_interval: 86400
