# Pi-Hole Ad Blocking
# Add PiHole URL in your secrets.yaml file. http://192.168.x.xx/admin/api.php
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'pihole'

    sensor.ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent
    sensor.domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb
    sensor.ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb
    sensor.dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text
    sensor.unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval
    sensor.queries_forwarded:
      friendly_name: Queries Forwarded
      icon: mdi:arrange-send-backward
    sensor.queries_cached:
      friendly_name: Queries Cached
      icon: mdi:animation

group:
  pihole:
    name: Ads Blocked
    entities:
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - sensor.unique_domains
      - sensor.queries_forwarded
      - sensor.queries_cached

sensor:
  - platform: rest
    name: dns_queries_today
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.dns_queries_today }}'
  
  - platform: rest
    name: domains_being_blocked
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.domains_being_blocked }}'
  
  - platform: rest
    name: ads_blocked_today
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.ads_blocked_today }}'
  
  - platform: rest
    name: ads_percentage_today
    resource: !secret sensor_pihole_url
    value_template: '{{ "%0.2f" % (value_json.ads_percentage_today |float) }}'

  - platform: rest
    name: unique_domains
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.unique_domains }}'
    
  - platform: rest
    name: queries_forwarded
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.queries_forwarded }}'
    
  - platform: rest
    name: queries_cached
    resource: !secret sensor_pihole_url
    value_template: '{{ value_json.queries_cached }}'
